/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import conexiones.conexionSQL;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carreto
 */
public class frmMiCRUD extends javax.swing.JFrame {
     
    //creamos la conexion a la base de datos
	conexionSQL cc = new conexionSQL();
	Connection con = cc.conexion();

    /**
     * Creates new form frmMiCRUD
     */
    public frmMiCRUD(){
        initComponents();
		mostrarDatos();
		getContentPane().setBackground(new java.awt.Color(60, 63, 65));
		//frmMiCRUD.setBackground(Color.red);
		//JFrame.setBackground(new Color(44, 56, 64));
    }
    
	public void limpiarDatos(){
		txtAPELLIDO.setText("");
		txtNOMBREALUM.setText("");
		txtCALIFICACION.setText("");
		txtCURSO.setText("");
    }
	
	public void insertarDatos(){
        try{
            String SQL = "insert into alumnos2 (nombres,apellido,materia,calificacion) values(?,?,?,?)";
            
            PreparedStatement pst = con.prepareStatement(SQL);
            
            pst.setString(1, txtNOMBREALUM.getText());
            pst.setString(2, txtAPELLIDO.getText());
            pst.setString(3, txtCURSO.getText());
            pst.setString(4, txtCALIFICACION.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Registro Exitoso");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al Registrar");
        }
    }
	
	public void EDITAR(){
		try{
			String SQL = "update alumnos2 set nombres =?, apellido =?,materia=?, calificacion =? where idalumnos = ?";

			int filaSelect = jtablaAlumnos.getSelectedRow();
			String id = (String) jtablaAlumnos.getValueAt(filaSelect, 0);
			PreparedStatement pst = con.prepareStatement(SQL);

			pst.setString(1, txtNOMBREALUM.getText());
			pst.setString(2, txtAPELLIDO.getText());
			pst.setString(3,txtCURSO.getText());
			pst.setString(4, txtCALIFICACION.getText());
			pst.setString(5, id);
			pst.execute();
			
			JOptionPane.showMessageDialog(null,"Registro Actualizado Exitosamente");

		}catch (Exception e){
			JOptionPane.showMessageDialog(null,"Error al Registrar");
		}
	}
	
	public void mostrarDatos(){
		String[] titulos = {"ID","nombres","apellido", "materia", "calificacion"};
		String[] registros = new String[7];
		DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        
        String sql = "select * from  alumnos2";
        try{
			Statement  st = con.createStatement();
			ResultSet  rs = st.executeQuery(sql);
        
			while(rs.next()){
				registros[0] = rs.getString("idalumnos");
				registros[1] = rs.getString(("nombres"));
				registros[2] = rs.getString("apellido");
				registros[3] = rs.getString("materia");
				registros[4] = rs.getString("calificacion");
				modelo.addRow(registros);
			}
        
			jtablaAlumnos.setModel(modelo);
        } catch (Exception e){
			JOptionPane.showMessageDialog(null, "Error al mostrar Datos" + e.getMessage());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensaje = new javax.swing.JLabel();
        lblNOMBRE = new javax.swing.JLabel();
        txtNOMBREALUM = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtAPELLIDO = new javax.swing.JTextField();
        lblCURSO = new javax.swing.JLabel();
        txtCURSO = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCALIFICACION = new javax.swing.JTextField();
        cmdGUARDAR = new javax.swing.JButton();
        cmdEDITAR = new javax.swing.JButton();
        cmdELIMINAR = new javax.swing.JButton();
        cmdNUEVO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaAlumnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMensaje.setText("Prueba constructor");

        lblNOMBRE.setText("Nombre del Alumno:");

        txtNOMBREALUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMBREALUMActionPerformed(evt);
            }
        });

        lblApellido.setText("Apellido del Alumno:");

        txtAPELLIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAPELLIDOActionPerformed(evt);
            }
        });

        lblCURSO.setText("Curso:");

        txtCURSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCURSOActionPerformed(evt);
            }
        });

        jLabel1.setText("Calificacion:");

        txtCALIFICACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCALIFICACIONActionPerformed(evt);
            }
        });

        cmdGUARDAR.setText("Guardar");
        cmdGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGUARDARActionPerformed(evt);
            }
        });

        cmdEDITAR.setText("Editar");
        cmdEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEDITARActionPerformed(evt);
            }
        });

        cmdELIMINAR.setText("Eliminar");
        cmdELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdELIMINARActionPerformed(evt);
            }
        });

        cmdNUEVO.setText("Nuevo");
        cmdNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNUEVOActionPerformed(evt);
            }
        });

        jtablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablaAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(cmdGUARDAR)
                                .addGap(18, 18, 18)
                                .addComponent(cmdEDITAR)))
                        .addGap(34, 34, 34)
                        .addComponent(cmdELIMINAR)
                        .addGap(18, 18, 18)
                        .addComponent(cmdNUEVO)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNOMBREALUM, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCURSO, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCALIFICACION, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblApellido))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblCURSO))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblNOMBRE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNOMBREALUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblApellido)
                        .addGap(18, 18, 18)
                        .addComponent(txtAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCURSO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCURSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCALIFICACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMensaje))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdGUARDAR)
                            .addComponent(cmdEDITAR)
                            .addComponent(cmdELIMINAR)
                            .addComponent(cmdNUEVO)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGUARDARActionPerformed
       insertarDatos();
        mostrarDatos();
    }//GEN-LAST:event_cmdGUARDARActionPerformed

    private void cmdNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNUEVOActionPerformed
     limpiarDatos();
    }//GEN-LAST:event_cmdNUEVOActionPerformed

    private void cmdEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEDITARActionPerformed
     EDITAR();
        mostrarDatos();
    }//GEN-LAST:event_cmdEDITARActionPerformed

    private void jtablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaAlumnosMouseClicked
        // TODO add your handling code here:
        int filaSelect = jtablaAlumnos.rowAtPoint(evt.getPoint());
        txtNOMBREALUM.setText(jtablaAlumnos.getValueAt(filaSelect, 1).toString());
        
        txtAPELLIDO.setText(jtablaAlumnos.getValueAt(filaSelect, 2).toString());
        
        txtCURSO.setText(jtablaAlumnos.getValueAt(filaSelect, 3).toString());
        
        txtCALIFICACION.setText(jtablaAlumnos.getValueAt(filaSelect, 4).toString());
    }//GEN-LAST:event_jtablaAlumnosMouseClicked

    private void cmdELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdELIMINARActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cmdELIMINARActionPerformed

    private void txtNOMBREALUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMBREALUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMBREALUMActionPerformed

    private void txtAPELLIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAPELLIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAPELLIDOActionPerformed

    private void txtCURSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCURSOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCURSOActionPerformed

    private void txtCALIFICACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCALIFICACIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCALIFICACIONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdEDITAR;
    private javax.swing.JButton cmdELIMINAR;
    private javax.swing.JButton cmdGUARDAR;
    private javax.swing.JButton cmdNUEVO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtablaAlumnos;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCURSO;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNOMBRE;
    private javax.swing.JTextField txtAPELLIDO;
    private javax.swing.JTextField txtCALIFICACION;
    private javax.swing.JTextField txtCURSO;
    private javax.swing.JTextField txtNOMBREALUM;
    // End of variables declaration//GEN-END:variables
}
